[package]
name = "campaign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = { version = "0.30.2", features = ["unstable-rendered-line-info"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
